### ISSUE TITLE
QA Toolkit - Update User Profiles & Project Record

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#200]
• Revisit User profiles and accessing the project record.  – LOW PRIORITY

**Comment by slmessier** [comment]
Tad - please elaborate to more clearly define the intended specifications - thank you!

**Comment by Tad-Daniel** [comment]
My thought is that I would like to allow user to see all of the project record information by utilizing the edit icon ![gr20edit](https://cloud.githubusercontent.com/assets/7913678/8257932/10fce202-167f-11e5-98fd-a14907d020dc.png) instead of just limited information.  Currently the user have to use the view icon ![gr20view](https://cloud.githubusercontent.com/assets/7913678/8257951/451ddbe0-167f-11e5-94f5-c1954b4376cf.png) to see all of the information.  

When using the edit icon can certain elements be hidden or removed to allow the role to see all of the information but only save specific items. see markup below.

![roles button removal](https://cloud.githubusercontent.com/assets/7913678/8258039/ed4dbf56-167f-11e5-9912-033587e3f77e.png)

**Comment by slmessier** [comment]
this issue has been superseded by GH #319  and will be closed at this time.
