### ISSUE TITLE
QA Toolkit- Tracking Systems- Develop new Yellow Card certification tracking system- Update project record role fields

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#262]
1)	Enhance the current project details page to have the following updates:
  a.	Add a select box next to the “Project Rep” textbox, and two text boxes for Yellow Card Certification and Expiration date. 
  b.	The select box when clicked should open a pop up that has a picklist of Project Reps to choose from.
  c.	Upon choosing one, the name should be available in the text box.
  d.	Corresponding Yellow Card Certification and Expiration date of that user must be automatically populated in the other two text boxes.  These text boxes will not be editable. 
2)	Repeat the same for ESC Manager and Superintendent.

![2de1](https://cloud.githubusercontent.com/assets/14997365/15326927/bda1b38a-1c1d-11e6-960f-54dc2cfefce0.jpg)

(Note: this issue was originally requested as No.2(d &e) and archived within GH issue #255 of this repository)

**Comment by vijme** [comment]
Implemented in dev, please test

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
Currently the system allows the user to edit and save the text value that is populated for the Representative Name (Project Rep / ESC Manager / Superintendent) after having selected a user from the associated pre-populated list. **Please update the system so that representative names are managed exclusively through the selection workflow, and cannot be edited as free text otherwise.**

![image](https://cloud.githubusercontent.com/assets/4098544/15516213/cdccaee8-21bf-11e6-96d8-d44dd6a3be32.png)

**To replicate the issue:**
1. Access Project details as an authorized user with YC management capabilities
2. For any one of the representative fields, use the selection process (shown below) to select a user of the system to associate as the representative. Save to commit changes. ![image](https://cloud.githubusercontent.com/assets/4098544/15516437/de46e1b6-21c0-11e6-9c2c-2f702aa01d61.png)
3. Begin typing over top of the text value within the associated representative user input field and click save to commit.
4. The system will allow the edit changes to be committed to the database resulting in a value that is not consistent with the users of the system.

**Comment by vijme** [comment]
Scott, the text box is available to accommodate the names that were saved for the existing records that are currently in the database. And which is why we decided to use a text box and use a picklist for selecting names, if we needed to.

**Comment by Tad-Daniel** [comment]
Working but,  The ESC Manager selection should be displaying the same list as the Superintendent selection (Contractor Role)  

The card number and date should also be showing in the "View details" section

**Comment by vijme** [comment]
ESC Manager selected reflected as Superintendent and view details section shows card number and date, in staging

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked "Ready for Production".

**Comment by Tad-Daniel** [comment]
Looks good but in the drop down menu can the names be Alphabetized, the order currently appears random

**Comment by vijme** [comment]
Fixed in dev. Minor change in db, can fix in production if needed

**Comment by Tad-Daniel** [comment]
Please do.

**Comment by vijme** [comment]
Implemented in staging and production

**Comment by Tad-Daniel** [comment]
Looks good
