### ISSUE TITLE
QA Toolkit - Incentives/Damages Enhancements - Implement Validation Checks to Support Enhanced Workflow

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#268]
![image](https://cloud.githubusercontent.com/assets/4098544/15580067/45ab9340-2335-11e6-8671-27c7e8fb6eb2.png)

(Note: this issue was originally requested as No.3 and archived as No.3-4 within GH issue #255 of this repository)

**Comment by rwingender** [comment]
This issue has been tested and validated in Dev with the following changes:
a) the error message marked as item A in this Github issue has been left out because it is not necessary.
b) the error message marked as item B has been changed to "Error: NTP Milestone Date not specified for the project".
c) the error message marked as item C has been changed to "Error: NTP Date already exists for the project".

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
