### ISSUE TITLE
(13.A.10) - QA Toolkit - Re-organize visual layout of Project record attribute fields

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#330]
**Re-organize visual layout of Project record attribute fields to a more intuitive representation**
_(Launch Point = Project Details)_

**Enhancement Specification(s):**

1. Relocate (2) checkboxes to be displayed with the other checkboxes
   - Wetlands and Waterways
   - Severe Weather
2. Narrow horizontal width of Yellow Card and EXP date input fields ; move fields left to recover horizontal space where checkboxes were previously located
![image](https://cloud.githubusercontent.com/assets/4098544/26423659/774dfcaa-409c-11e7-97bd-e413592f3622.png)
![image](https://cloud.githubusercontent.com/assets/4098544/26467986/c3361118-4162-11e7-9a37-8922916c20e7.png)
_Tracking Note: this issue was originally requested as **No. 13.A.10 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Due to the toolkit limitations, the QA related information are grouped together. I have moved Project Date to above the comment box and the check boxes relocated. And also define width so that the components no longer shuffle when the screen width is minimized. Please let me know if this is okay. 

![image](https://cloud.githubusercontent.com/assets/6668314/26512325/115e5e28-4234-11e7-9a5e-84a506136961.png)

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
