### ISSUE TITLE
(13.B.4) - QA Toolkit - QA Inspection List By District PDF - Validate That Average Grade on the PDF is Consistent with UI

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#337]
**QA Inspection List By District PDF Enhancement**
_(Launch Point = BP/SS->Reports->QA Projects By District)_

**Enhancement Specification(s):**

1. Validate that the output for average grade on the PDF report is consistent with what is displayed in the UI system
2. Log results of investigation as a comment; include a description of any potential solution(s).

![averagegraderatingcheck](https://user-images.githubusercontent.com/23661339/26928321-bd4b062a-4c23-11e7-953d-aa0698c0cdb3.png)

**Comment by vijme** [comment]
Please find my detailed analysis here:

The launch point of the report is BP/SS->Reports->QA Projects By District.

Currently, BP/SS tab is visible only to ESC Manager profile. This profile has the role of "See All Projects". So in inspections tab, ESC Managers can see inspections of all projects. But QA Projects By District was listing the projects assigned to the user, irrespective of their profile. **So I went ahead and changed QA Projects By District to list all the projects**,  because ESC Managers are the ones who have access to this tab. Now the listing matched the inspections tab listing. _**Please advise if this is not the intended requirement and need to be changed.**_

As far as the grade calculation, it follows the following protocol. Please find a sample district grade report and its corresponding inspection tab details (in dev, after the above fix was implemented) 

![image](https://user-images.githubusercontent.com/6668314/27186048-317a1afe-51b5-11e7-85bd-7d8987909f0a.png)


![image](https://user-images.githubusercontent.com/6668314/27185992-0c4f631a-51b5-11e7-85d1-1ad163de02d1.png)


Inspection calculation includes both graded and ungraded inspections, but the grade calculation includes only graded inspections to calculate average. In the above example, for contract 0000000, inspections count is 5 and the grade was calculated as (0+0+62.2+93+80)/5 = 235/5 = 47. For contract 9876543, inspection count is 4, the grade was calculated as (84+85)/3(not 4) = 169/3 = 56.3. 

_**Please let me know if this method of grade calculation needs any changes.**_

**Comment by slmessier** [comment]
**Tad - please test as-needed to confirm**:

**1. UI information now matches PDF Report output and otherwise appears as you expect it to
2. confirm the formula referenced by the system to automatically calculate grade. itemize any revisions required as a list.**

Thank you!

**Comment by Tad-Daniel** [comment]
The report looks good and from what I see the calculations are correct...

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
@Tad-Daniel can this be closed? thank you!

**Comment by Tad-Daniel** [comment]
Yes, This issue is complete
