### ISSUE TITLE
QA Toolkit - Update System Logic for Managing User Notification Subscriptions

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#350]
### Required Enhancement Specification(s): 
1. Combine the site condition notification selections in account and user settings. **Consolidate the existing Site Condition Values to a standardized 3-category rating system**:
    - **Compliance**
    - **Needs Correction**
    - **Non-Compliance**
 
![image](https://user-images.githubusercontent.com/4098544/29335369-6600e066-81d8-11e7-9a41-4709110a24db.png)

2. **Update notification subscription logic to omit user accounts that are actively disabled** from all outbound email notifications.

3. **Update notification subscription logic to function consistently with the logic for Grade Notifications**. 

_Tracking Note: this issue was originally requested as **No. 14.F within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343 of this repository._

**Comment by vijme** [comment]
@slmessier, can you please elaborate on point no 3 above, i don't actually remember what it was

**Comment by vijme** [comment]
@Tad-Daniel 
For Point No. 1 above, to combine the site condition notification, does it require that the "Satisfactory Compliance" and "Non Satisfactory Compliance" site conditions text to be changed to "Compliance" and "Non-Compliance" on 00C61.1 inspection form? Or is it just required only on the subscriptions page ?

How do you think we need to map the existing data? For example, if a user has an existing subscription to "Compliance" for QA1 and "Non-Compliance" for OOC61, how is it required to display in the current system?

**Comment by Tad-Daniel** [comment]
Only on the subscription page. The OOC 61.1 is no longer utilized so there is no need to update it.  As for the mapping the best way may be that if they have it checked for any of the forms then it will now apply to all.  In your example the user would end up with a check in both the "compliance and "non-compliance " for both forms.

**Comment by vijme** [comment]
@Tad-Daniel , Thanks for the clarification. I have just updated the subscription page according to the specifications. For the current subscription records, on loading, UI checkboxes has a check, if they had corresponding items checked on any of the forms. On Save, the site condition will be updated for all ALL inspection types.

However since these records are not updated in the database, existing subscription will still be the same, i.e) though they would see a check in compliance, they might not get notifications for compliance for all inspection types, they would get only for what they have subscribed till now. To address this, two things can be done: 1. The admin or the user has to UPDATE/SAVE their subscription once again. 2. We can update the subscription records in the production database directly during deployment. I checked prod DB this morning and looks like there are only a few of them to be updated. 

The admin -> user edit page in dev is updated with the change. It also has the original UI (to check it works, will remove it later). Please let me know your thoughts, after which I will update the settings page, new user request and new user response pages. Thank you.

**Comment by vijme** [comment]
@slmessier, can you please elaborate on point no 3 above

**Comment by Tad-Daniel** [comment]
Not sure.   Reading it I am a bit confused with what I wanted.  I think what you have developed is what I was hoping for. My only comment at this time is now that the new simplified selections a re available the old separated template option can go away as not to confuse the users

![x out](https://user-images.githubusercontent.com/7913678/30430843-83ae72f4-992a-11e7-8077-317bcb18c24f.png)

**Comment by Tad-Daniel** [comment]
I had a moment of clarity this morning.   What I meant in #3 above was to ensure the other notification system all worked the same as the grade notification system.  Specifically the modification notification system logic.

**Comment by vijme** [comment]
Previous Email Summary For Reference

------------------------------------------------------------------------------------------------------------------
From: Scott Messier [mailto:Scott.Messier@kci.com] 
Sent: Monday, September 18, 2017 11:09 AM
To: Tad Daniel <tdaniel@sha.state.md.us>
Cc: Viji Selvamani <viji.selvamani@ecointegration.com>
Subject: RE: [kcigeospatial/sha_oed_issues] QA Toolkit - Update System Logic for Managing User Notification Subscriptions (#350)

Good Morning Tad,

In order to be clear on specification, I wanted to follow up on some of the details associated with this request (#350).

Could you please confirm your request is:
•	To update the user workflow for managing the Modification Subscription checkbox on the user page, so that users may configure the checkboxes for each project distinctly using the associated project dropdown menu, as is currently made possible for the grade notifications. Please reference the attached graphics as needed to support your valuation. 

If my understanding is not accurate, please provide some additional insight. I can set up a call if necessary. However, I’m hopeful that my understanding is accurate and you’ll be able to confirm.

Please let me know if you have any questions – thank you!

-------------------------------------------------------------------------------------------------------------------
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Monday, September 18, 2017 1:09 PM
To: Scott Messier <Scott.Messier@kci.com>
Cc: Viji Selvamani <viji.selvamani@ecointegration.com>
Subject: RE: [kcigeospatial/sha_oed_issues] QA Toolkit - Update System Logic for Managing User Notification Subscriptions (#350)

Yes you are on the right track but the big issue is that when a user subscribes to be notified on all modification emails they do not get them

Example:   If someone goes and select to receive notifications for A and B grades then by default they get all A and B emails for all projects  assigned -  If someone goes and does the same for modifications then the same does not apply, they do not get the emails as expected.

------------------------------------------------------------------------------------------------------------------

**Comment by vijme** [comment]
**MOD NOTIFICATIONS WORKFLOW:**

### MOD REQUEST NOTIFICATION RECIPIENTS:

ACTIVE USERS IN:
1. Request Creator
2. Contractor (if available)
3. SHA/PE (if available)
4. Project Users who have subscribed for Mod request and response 
	notification for ALL Projects or that specific project.
5. Package Approvers

(The above 5 will be added to the mod request recipients table in database for a MOD)


### MOD RESPONSE NOTIFICATIONS

1. In UI, all active project users will be listed in nofications textbox
2. The above mod request recipents will have their checkbox checked by default. If user 
   unchecks them, they will not recieve the current notification ONLY. They will still be 
   checked for future responses
3. Other project users will not have their checkboxes checked. When checked in UI, the 
   user will be added to the recipient table and continue to recieve notifications 
   from then on. 
4. If MOD was approved, the project users who have subscribed for "Approvals notifications"
   for "ALL PROJECTS" or that specific project will be added to the recipient list.

**Comment by vijme** [comment]
@HollySchuelerKCI  The above issue can be validated in dev using the admin->analysis->notification log tab to check the list of recipients. (since notifications does not work in dev)

Item 1, 2 and 3 completed in dev.

**Comment by vijme** [comment]
@Tad-Daniel On a separate note, QA Concurrence had all the users in the system listed in their notify checkboxes (all unchecked). I just changed to list all Active Project Users instead of all the users in the system. Should that be good?

(The logic in QA concurrence  is very simple, the user needs to select the notification users every time a request or response is saved.)

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
I ran though several accounts and this seems to be functioning correctly.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Appears to be working correctly.

I do have one question, do the QA concurrence request automatically goto the assigned QA inspector.  I thought they did prior.

**Comment by vijme** [comment]
Sorry, please find the QA Concurrence subscription list
- Request creator
- Users who have subscribed to MOD Request and approvals (same like MODS)
- If approved, users who have subscribed to MOD approvals. (same like MODS)
- **Any project user who has the checkbox checked, they are still added to the future communication though appears to be unchecked in UI for subsequent responses.**

**Comment by vijme** [comment]
Please apologize again, i have corrected the above findings.

**Comment by Tad-Daniel** [comment]
Excellent, thanks

**Comment by Tad-Daniel** [comment]
Still evaluating but everything is looking good

**Comment by Tad-Daniel** [comment]
The response I have gotten back from the team is that this is functioning correctly and as expected now.
