### ISSUE TITLE
QA Toolkit Task 18 - Progressive Scheduling System - UI & Miscellaneous Enhancement Specification

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#380]
### Enhancement Specification Overview
The following material represents the miscellaneous specification that supports development of the Progressive Scheduling functionality. Please develop and/or test against the following 4 specification requirements distinctly.

### New QA1 Inspection Value
1. **Add (1) new value to the list of values that exist as options within the QA Inspection Priority dropdown field (on the project record): _"Progressive"_** 
 ![image](https://user-images.githubusercontent.com/4098544/34794549-01405ba2-f61d-11e7-9f85-d12760a8696c.png)

### Trigger for Automation
2. The automated system routine to update inspection scheduling interval will be **triggered when an inspection is created or saved** 
       **_QA1 Inspection page – Save Button_**
![image](https://user-images.githubusercontent.com/4098544/34794730-96d4039e-f61d-11e7-8646-743ef5ffaf40.png)

### System Check for Incentives
3. The system check for **“Projects with Incentives” is defined as where “Final Incentive” is 0 or <> 0**
![image](https://user-images.githubusercontent.com/4098544/34794578-1ea72108-f61d-11e7-8c4d-483405676112.png)

### Open Projects Apply
4. Mention of the term "Projects" refers to projects with status = open across all Task 18 specification. **Automation of QA1 Inspections for closed projects using the enhanced, progressive scheduling capability is not required within this specification.** 

### Make Inspection Date NOT Editable
5. As a result of collaborative discussion on 2/2/2018 with stakeholders: **The Inspection Date on QA1 inspection form is to become NOT editable.** 

_Tracking Note: this issue was developed through discussion regarding specification originally requested as **Nos. 1 thru 4 within the Task 18 Scope of Work Agreement**, and as referenced within GH issue #377 of this repository.

**Comment by vijme** [comment]
@Tad-Daniel : 

Looks like there is an existing logic to get the new inspection schedule:

Three dates are compared to determine the next schedule (Last inspected date, Activated date after hold, inspection skipped date).

1. (Most Common Scenario) If the last inspected date is greater than inspection skipped date and activation date of the hold inspection, then the next inspection schedule is defined based on last inspection date. **This is again internally based on grade, if "C" or "D", then the scheduled is defined to be 3 days after last inspection date, otherwise, the schedule follows the value from the inspection priority dropdown.**

2. If the activation date of the hold inspection is greater than inspection skipped date and last inspection date, then the next inspection schedule is defined to be the next day of activation date.

3. If the inspection skipped date is greater than last inspection date and activated date, then the next inspection schedule is defined to the next day of inspection skipped date.

The new implementation will change the logic of the bolded text only. All other rules still remain the same. Please let me know if otherwise.

Thanks.

**Comment by Tad-Daniel** [comment]
We have to keep that bolded logic working also.  The specs call for a follow-up inspection within 72 hours of a C or D grade. So the logic must account for the follow-up. After the follow-up has been completed then the priority dropdown resumes.

**Comment by Tad-Daniel** [comment]
Correct "F" grade do not have an associated timeframe.

**Comment by vijme** [comment]
Alright, thanks for that clarification

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
The above points have been validated by the project team and confirmed by the stakeholder. This issue is ready for staging.

**Comment by HollySchuelerKCI** [comment]
The above has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Appears to be working correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder and is ready for Production.

**Comment by Tad-Daniel** [comment]
Currently testing in production on project MD8675309

**Comment by Tad-Daniel** [comment]
So far everything seems to be working well in productions but I have found one unexpected issue.  The schedule grid defaults to 14 days so therefor the projects beyond that do not show.  The default should be 31 days to ensure everything shows all the time.
![image](https://user-images.githubusercontent.com/7913678/39248818-194ec21a-486b-11e8-804f-caee234c2dbd.png)

**Comment by vijme** [comment]
The change is very minimal. Implemented in dev. Can implement in STAGING if advised.

**Comment by HollySchuelerKCI** [comment]
The above issue reported by Tad to change the default days from 14 to 31 has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Sounds good, lets do it.

**Comment by vijme** [comment]
Implemented in staging

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Appears to be working well in production  Issue can be closed

**Comment by Tad-Daniel** [comment]
Item completed
