### ISSUE TITLE
QA Toolkit - Updates to Both SWM and Modifications

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#390]
# Enhancement Specification Overview
The following material represents the common updates to both the SWM and Modification Sections as outlined in Task 19 SOW.

## SWM and Modification Section Updates

1. When responding to SWM requests and Modifications show the prior responses in the lower section of the screen like the communication system does 
![image](https://user-images.githubusercontent.com/25441512/38102935-d240cc6a-3352-11e8-8fc5-ffa77d7a2c5e.png)

2. Adjust the font size and color of the “Package” and “Final Mod Status” to be more prevalent on the page.
     - Package status font is blue for all conditions
     - In Final Mod Status the font color for Approved is Green, Denied is Red, Withdrawn is Black and Pending / Submitted for Review are Blue
![image](https://user-images.githubusercontent.com/25441512/38102851-85c3941c-3352-11e8-8e5d-d8f306dcf324.png)

5. Remove the word “Request” from all instances of “upload request document”

**Comment by vijme** [comment]
Items 2 and 3 implemented in dev. 

Fort item 1, have included MOD responses in the page. Need more information.
- Should the previous responses grid be available for a new response Or should they be showed up for viewing an existing response?

- The response grid is added below the SAVE button currently in MOD Response page. Please let me know otherwise.

- The response user and response text is been shown up currently. Any other fields need to be added?

![image](https://user-images.githubusercontent.com/6668314/38579204-4197fe6e-3cd4-11e8-9ce9-28f8c189c84f.png)

**Comment by Tad-Daniel** [comment]
Everything works as expected and I think it is good.  The way it works for a new first response is fine. One addition, please add the mod # to top of the response grid so users have a reference. Otherwise I like it.

![add mod number](https://user-images.githubusercontent.com/7913678/38623193-fdf04ece-3d72-11e8-8389-378e530fd418.png)
d.

**Comment by vijme** [comment]
Implemented in MOD, QA Concurrence and SWM. New responses will show all responses underneath. Existing responses will show only responses previous to them.

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project team in the Development environment.

**Comment by Tad-Daniel** [comment]
Looks good.

**Comment by HollySchuelerKCI** [comment]
Further specfications confirmed in meeting held on 4/12/2018:

### For displaying ‘Request #’ on applicable UI grids:
•	Modifications Grid – YES
•	QA Concurrence Grid – No
•	SWM Grid – No


### For displaying previous modification response information:
•	New Mod Request – display all responses for preceding request
•	Existing Mod Request - display only the single response that precedes prior

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by the stakeholder in the Staging Environment.

The updated status of this issue = _Ready for Production_

**Comment by Tad-Daniel** [comment]
Help button issues has occurred with the recent update same as the SWM sub-tab,  
The help button appears when you guys upload it but as soon as I upload a new version with the exact same name the button goes away and nothing I do will bring it back.

**Comment by Tad-Daniel** [comment]
This issue has been resolved.  I just verified tht everything is working correctly
