### ISSUE TITLE
QA Toolkit - Touch Friendly GUI

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#397]
# Enhancement Specifications
The following material represents the Project Record Changes as outlined in Task 20 SOW.

## Touch Friendly GUI Adjustments
The stakeholder would like to update the following:

1. Add a 2 blank lines to bottom of all pages to resolve an MS Edge issue.
2. Move delete buttons to far right of column
![image](https://user-images.githubusercontent.com/25441512/38140598-7cecc4b6-3402-11e8-907d-b9b02a1be4e0.png)

**Comment by vijme** [comment]
Implemented in dev. Also added 2 px padding for buttons in QA-1, QA-2 and projects page. Let me know if any changes needed. Thanks.


Original request attached for tracking purpose.


Scott
 
I noticed Viji is working through the touch friendly parts of the current task and so far I like what I see.  In a meeting prior we discussed padding around the buttons for people with fat fingers like me and a concern was mentioned about major page and grid adjustments.  Due to the concerns we dropped this portion of the task.  I would like for you guys to reconsider the option. I adjusted the padding to 2px on each side to the buttons  on the following grids and the button movement was flexible enough that there was no misalignments In the project list grid you can see the difference the 2x all the way around makes.  I did these by changing the CSS instead of a maculated image so the effects would be real.  Could this be accomplish under the current task, please consider.
 
Maybe give it a try for me and if your hit any complications we will back off and I will drop it.
 
Let me know
 
 
 
 
 
Thanks

**Comment by Tad-Daniel** [comment]
SO far this looks good in DEV as checked in two different browsers.

Looks good on schedule, QA-2 and projects page.
Does not appear to be on the QA-1 page.
Please implement on the permits, permits details and permits templates pages
Please implement on the non-compliance and skipped inspections pages (BPSS)
Please implement on user list and standard forms pages (admin)
Please implement in all subtabs of the project record.

If these changes will negatively impact the planned rollout timeframe then they can be delayed until a future rollout,

**Comment by slmessier** [comment]
@Tad-Daniel ; @vijme 

1. **The spacing within the existing DEV release will be applied to QA-1 Page**

2. **The requested implementation across the additional pages outlined above would impact the deployment schedule and will be postponed until a future release.** The additional requests will be represented in a new GH issue so that they can be tracked distinctly.

**Comment by Tad-Daniel** [comment]
Sounds good

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team and confirmed by the project stakeholder.

The status of this issue is "Ready for Staging"

Further enhancements requested by the stakeholder have been added to GitHub #404 will be addressed in a future release

- Please implement on the permits, permits details and permits templates pages
- Please implement on the non-compliance and skipped inspections pages (BPSS)
- Please implement on user list and standard forms pages (admin)
- Please implement in all subtabs of the project record.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item complete
