### ISSUE TITLE
QA Toolkit - Update Button Graphics

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#401]
# Enhancement Specifications
The following material represents the enhancement to update the button graphics for Documents Submenu - Search Filter buttons as stated in the Task 20 SOW.

## Update Button Graphics: Project List – Documents SubMenu - Search Filter buttons

1. Update button to more recent graphic icon utilized elsewhere in sub-tabs
![image](https://user-images.githubusercontent.com/25441512/38142069-ebe34042-3408-11e8-8d24-6b0915c8ee7d.png)

**Comment by vijme** [comment]
Fixed in dev. Fixed some other buttons  under resources and milestone subtabs shown below

![image](https://user-images.githubusercontent.com/6668314/39877350-bdc47946-5443-11e8-975a-c732f9e1db85.png)

![image](https://user-images.githubusercontent.com/6668314/39877384-d8bd886e-5443-11e8-83bf-af36d0a45855.png)

Also changed buttons in Schedule sub tab when clicking Delay and Suspend buttons

![image](https://user-images.githubusercontent.com/6668314/39877487-130d34ba-5444-11e8-9580-20e07be35da9.png)

![image](https://user-images.githubusercontent.com/6668314/39877522-2639f564-5444-11e8-9f60-fa5908fb8eaa.png)

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
