### ISSUE TITLE
SSRS Conversion: IEM2 - DailyInspectionReport

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#446]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Log into the EM Toolkit
2. From the inspections Tab, select a project from the list
![image](https://user-images.githubusercontent.com/25441512/45625143-2d062300-ba5a-11e8-9dfc-ffb6dfa3c06d.png)
3. From the Daily Inspection List, click the print button for the desired date.
![image](https://user-images.githubusercontent.com/25441512/45625224-5626b380-ba5a-11e8-9ac7-92bb2795080c.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM2 - DailyInspectionReport.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398394/IEM2.-.DailyInspectionReport.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45625313-8706e880-ba5a-11e8-8cec-01afe4401541.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding this report.
First note that there is a second way to generate this report:
1) Log into the EM Toolkit.
2) From the inspections Tab, select a project from the list.
3) From the Daily Inspection List, click now on the first "Print Preview" button for the desired date.
4) Go to the bottom of this page and click on the shown "Report" button.

Note also that in order to see data in the "Issues:" section, I used on the 3rd page the top "I-95/I-695 Interchange General Purpose Roadways and Ramps" project, and its first "9/30/2011" inspection.

Note also that for the "Permit Review:" section, I used the 4th project shown in the 1st page, the "ICC Western Maintenance Facility" project. The original report would duplicate/repeat several times the shown 
main green-colored permit names and numbers. For example the "U.S. Army Corps of Engineers Individual Permit" and "05-60011-1" would be shown several times, fairly confusing! I now show those only once, and I sort inside of them by these permit names and numbers.

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Please make one minor adjustment. Please reduce the font size by 1 or 2pts for the Disclaimer section.  See area below in screenshot.

![image](https://user-images.githubusercontent.com/25441512/50599952-8d8c6500-0e7d-11e9-88a6-0a4150d39293.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now made this change, I used 8pt font size, 1pt less.
I merged my changes the "master" and the "viji-reports" branches, so it will be released soon.

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[IEM 2 - DailyInspectionReport - 446 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2723938/IEM.2.-.DailyInspectionReport.-.446.-.FINAL.OUTPUT.pdf)

**Comment by sgpapakirk** [comment]
Sorry @HollySchuelerKCI, to be consistent with the https://github.com/kcigeospatial/sha_oed_issues/issues/449 ticket, I have now made the Disclaimer fields to be little smaller, 7.75pt.
Viji will deploy it soon.

**Comment by HollySchuelerKCI** [comment]
This update has been validated by the project team.

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
