### ISSUE TITLE
SSRS Conversion: IEM5 - IssInsp

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#451]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the EM Toolkit --> Inspections Tab, select a project
2. Click the Issues Tab
3. From the Issue List, click the print button in the right column
4. Click Issue Inspections
![image](https://user-images.githubusercontent.com/25441512/45761351-11398300-bbfa-11e8-8b47-17a56694d5ad.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM5 - IssInsp.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398430/IEM5.-.IssInsp.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45761550-75f4dd80-bbfa-11e8-91a4-96788068e07b.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding this report.
First note that there is a second way to generate this report:
1) Log into the EM Toolkit.
2) From the Inspections tab, select a project from the list.
3) Click now on the Issues tab.
4) From the Issues list select a record, and click on its second "Edit" (pencil) icon.
5) Go to the bottom of this page and click on the shown "Report" button.
6) In the shown popup click on the "IssueInspections" link.

Note:
1) There is Draft watermark that is used in each "Daily Inspection Report" section, which can be multiple pages. It shows only when InspectionDetails.INSP_FINAL is not 1.
The top "Issue Details & Inspection History" section doesn't show this Draft watermark.
2) In the "Permit Review:" area, which is in each "Daily Inspection Report" section, I couldn't easily for now 
make its grouped headers to be repeated  on multiple pages.
For example this is ones:
    U.S. Army Corps of Engineers 05-60011-1
    Individual Permit
Now if the data below it take more than 1 page, I don't repeat this header in each page as the original Crystal Report does.
If it's important, I can try to switch the report to use grids (tablix) vs. lists, because the grids have such extra properties.
BUT because I am not certain and didn't have much time, for now I decided to play it safe and progress like using lists in these areas.

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by vijme** [comment]
Deployed to dev

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Here are some comments based on testing:

1. Please fix alignment issues for Issue Number. It appears to be justified to the right. 
![image](https://user-images.githubusercontent.com/25441512/50992438-302f8e00-14e5-11e9-8a2c-c825d6d10de8.png)


Regarding the header comment above, we will wait for stakeholder feedback.

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI indeed I will fix this now! I just did this change minutes ago before Viji deployed. The original Crystal Reports was formatting this "Issue Number" field's data using 2 decimals, like say "3.00".
I removed this formatting, because in the system these are whole numbers.
I noticed say the my current https://github.com/kcigeospatial/sha_oed_issues/issues/452 : IEM6 -  IssueDetailsReport doesn't do such formatting with 2 decimals.

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI , Viji just finished deploying this small formatting fix.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good - accepted

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[IEM 5 - IssInsp - 451 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2770008/IEM.5.-.IssInsp.-.451.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
