### ISSUE TITLE
SSRS Conversion: IEM6 - IssueDetailsReprt

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#452]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the EM Toolkit --> Inspections Tab, select a project
2. Click the Issues Tab
3. From the Issue List, click the print button in the right column
4. Click Issue Details
![image](https://user-images.githubusercontent.com/25441512/45761351-11398300-bbfa-11e8-8b47-17a56694d5ad.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM6 - IssueDetailsReprt.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398436/IEM6.-.IssueDetailsReprt.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45762330-257e7f80-bbfc-11e8-8373-15cc64184bae.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding this report.
I jhave just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

Note that:
1) The original Crystal Report was never showing anything in the Status field!!
   I moved it first to the right side. I also now show its value by using the same STAT_NAME field
   as previous IEM reports do, but from the current "IssueDetails_Issue" data source.
2) The original Crystal Report was using Green for the below labels.
   I chose to keep them all Black, as they are in my previous IEM reports:
   A) Supporting Documents
   B) Inspections
   C) Comments
3) Within the 3 shown grids of the above 3 labels I now added a very thin (0.25 pt) black line
   to separate the records. I thought it's easier in the eye.
4) When there are no values under the above 2 first labels we show the following corresponding texts instead:
   A) No Documents Associated to this Issue
   B) No Inspections Associated to this Issue
   For these 2 the original Crystal Report was using bold and italic, I kept it normal and not bold either.  
   Additionally I added this similar text for the above 3rd "Comments" label:
   C) No Comments Associated to this Issue

Note also that in addition to the above "Steps to Generate Report", we have other 4 method callers
to the ReportGenerator.GenerateIssueDetailsReport method.
Now since I changed this method to use SSRS, it's pretty much guaranteed that all these other places
will also use SSRS now.
Say for example clickiing on the Edit (pencil) icon to open an issue and then clicking on the report button and finally clicking on the shown popup the "IssueDetails" link.
Only if you really want I can type up these other 4 places (callers).

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk This report looks good.  I do have one minor modification to the report.

It appears that when there are (2) plan sheets associated to the issue, it will overlap the Disclaimer statement. Can you add a space so that the two dont crowd the other?

I've taken a screenshot, which you will see below:

![image](https://user-images.githubusercontent.com/25441512/51131099-b6591680-17fc-11e9-93c6-473ebbc65e32.png)

**Comment by sgpapakirk** [comment]
Hello @HollySchuelerKCI. Indeed I was able to replicate this issue, which was primarily happening say with 2 Plan Sheets.
I have now set the VerticalAlign property to be "Bottom" in the "Disclaimer:" and the "Recommendations are made..." textboxes. Then I believe we will always have sufficient distance from the top "Plan Sheets" or the "Impact Plates" lists.
Please note that I have done in this small formatting change in these tickets, too:
1) https://github.com/kcigeospatial/sha_oed_issues/issues/446 : IEM2 - DailyInspectionReport
2) https://github.com/kcigeospatial/sha_oed_issues/issues/449 : IEM4 – EnvironmentalImpactReport
3) https://github.com/kcigeospatial/sha_oed_issues/issues/451 : IEM5 - IssInsp

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good, accepted

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[IEM 6 - IssueDetailsReport - 452 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2769991/IEM.6.-.IssueDetailsReport.-.452.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
