### ISSUE TITLE
SSRS Conversion: MDE7 - PostPermitting

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#467]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click Post Permitting from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45893562-a626b280-bd99-11e8-96f9-ff3e3968a9c6.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE7 - PostPermitting.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406163/MDE7.-.PostPermitting.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45893610-ca828f00-bd99-11e8-9831-8afc76ee9589.png)

**Comment by sgpapakirk** [comment]
(similar comments as in the 472 issue):
Holly, I have finished coding this report.

**Please note though this one limitation:** 
When you use the PDF export, there is no problem rendering of the small 1 sub-report grid that shows up in certain rows, under these 4 top header labels: "Permit", "Permit #", "Issued" and "Expires".
You can see such a sub-report grid in the record that has FMIS =2380203-B03700, and some other ones.
**But unfortunately, the current Excel export renders only the main grid rows, not this small sub-report grid in certain rows. I tried many approaches, and internet suggestions, but nothing worked.**
I had to use a sub-report to accomplish this report.
Now these are my errors in the 472 issue when I tried to use 2 grid tables within the main grid table instead:
1) "Subreports within table/matrix cells are ignored."
2) "Data Regions within table/matrix cells are ignored."

As far as I know now we actually use SSRS ver. 2005 which is fairly old.
I am positive that if we upgrade to at least 2008, 2010 or higher, this Excel issue will be fixed.

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by sgpapakirk** [comment]
Viji has deployed this report to http://oed.kci.com/shaportal

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, this is the first report that will now correctly produce both the PDF and the Excel files.
The PostPermitting.rdlc handles now only the PDF files. It's the original one and it uses a grid with a sub-report.
The new PostPermitting-Excel.rdlc handles only Excel files and it uses a list with sub-report, so that Excel can render the sub-report(s)' data, too.

I tried to use the newer PostPermitting-Excel.rdlc to also render PDF files, but it was leaving the main grid’s first row empty on the pages 2, 3, 4, etc. (a weird rendering issue that I couldn’t fix).

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by sgpapakirk** [comment]
Viji has now deployed this ticket's code changes in our http://oed.kci.com/shaportal web site.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk I found a discrepancy between the PDF and Excel versions. It seems that the Excel report does not include information from the following columns:

- Permit
- Permit #   
- Issued 
- Expires

#### PDF:
![image](https://user-images.githubusercontent.com/25441512/49757227-e8210f80-fc89-11e8-9171-fb686cddfef7.png)

#### Excel:
![image](https://user-images.githubusercontent.com/25441512/49757376-451cc580-fc8a-11e8-8166-dcc2394bf074.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I don't understand this, the subreport data should also be in the Excel file
1) I tested logging in the http://oed.kci.com/shaportal web site where Viji released it.
2) I went to the MDE Toolkit
3) I logged in with Viji's "vs" username.
4) I then clicked on the "Print" button, selected first the "Spreadsheet" format (Excel), also then clicked on the "Post Permitting" link.
I zipped the .xls file in here. I can definitely say that I see data in these columns!
[PostPermitting - Excel fixed in oed.kci.com.zip](https://github.com/kcigeospatial/sha_oed_issues/files/2664808/PostPermitting.-.Excel.fixed.in.oed.kci.com.zip)

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk I am now able to see the full report. Not sure what occurred earlier.

**Comment by HollySchuelerKCI** [comment]
This report, both PDF and Excel versions have been successfully validated by the project team in the Development Environment.

Sub-Reports were viewed successfully in both PDF and Excel versions of this report.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL OUTPUT REPORT SAMPLE:
[MDE 7 - PostPermitting - 467 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2699867/MDE.7.-.PostPermitting.-.467.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
