### ISSUE TITLE
SSRS Conversion: MDE8 - TeamLeader

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#468]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click Team Leader from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45894432-51d10200-bd9c-11e8-8ab2-20cac738d705.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE8 - TeamLeader.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406240/MDE8.-.TeamLeader.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45894485-7927cf00-bd9c-11e8-92b4-fb2bd2e6795f.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding so that we can now correctly produce both the PDF and the Excel files.
As I said in the Issue 467, I couldn't use say this new Excel .rdlc to produce also the PDF files because
it was leaving the main grid’s first row empty on the pages 2, 3, 4, etc. (a weird rendering issue that I couldn’t fix).

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
Both the PDF and Excel versions of this report has been successfully tested by the project team in the **_Development Environment._**

Sub-Reports were successfully incorporated into the Excel report.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[MDE 8 - TeamLeader - 468 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2723988/MDE.8.-.TeamLeader.-.468.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report including sub-reports have been validated by the project team in the **_Staging Environment._**
