### ISSUE TITLE
SSRS Conversion: MDE11 - WorkloadSRED

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#469]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click Worlkload SRED from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45895194-82b23680-bd9e-11e8-9f4b-22488bbded3b.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE11 - WorkloadSRED.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406278/MDE11.-.WorkloadSRED.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45895240-abd2c700-bd9e-11e8-9037-481347ba229e.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding so that we can now correctly produce both the PDF and the Excel files.
As I said in the Issue 467, I couldn't use say this new Excel .rdlc to produce also the PDF files because
it was leaving the main grid’s first row empty on the pages 2, 3, 4, etc. (a weird rendering issue that I couldn’t fix).

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by sgpapakirk** [comment]
I have noticed that Viji has actually deployed this report in our http://oed.kci.com testing web site.

**Comment by HollySchuelerKCI** [comment]
This report, both PDF and Excel versions have been successfully validated by the project team in the **_Development Environment._**

Sub-Reports were viewed successfully in both PDF and Excel versions of this report.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
This report, including sub-reports have been validated by the project team in the **_Staging Environment._**
